### PR TITLE
update files storage and db storage to get objects or count object

### PR DESCRIPTION
**Pull request by yook00627**
For db_storage and file_storage added get method to get objects that are specified with the id corresponding to the object we are trying to get. also added count method to count all object if class is not specified if it is just count all object with specified class.
For db_storage used session to get all objects from the database
For file_storage used __objects that contains all objects to get the right object

### CODE REVIEW

**Comment by Donnerschlag** [comment]
Everything looks fine, can I ask why you didn't combine cls and id in the get program from file_storage.db?

**Comment by Donnerschlag** [comment]
We also  don't have 2 tests for this program

**Comment by yook00627** [comment]
I will add test for file storage and db storage

**Comment by Donnerschlag** [comment]
Everything checks out. Going to merge

**Pull request merged**
